
### ================================
### variables
### ================================
@API_URL = http://localhost:5000
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NzYwOTM1NjYsImV4cCI6MTc3NjEwMDc2NiwiYXVkIjoiZXh0ZXJuYWwtc2VydmljZXMiLCJpc3MiOiJBcmNoZS1hcGkifQ.rFGBW8lp0oKq6L3UyLjSozc2W8n7hf8TOaZ5OPQEhT
### ================================



### prueba
GET http://localhost:5000/api/v1/ping
Accept: application/json

#### prueba token
GET http://localhost:5000/api/v1/auth/token?name=nulln&isActive=null&rolId=null
Accept: application/json


# ==============================================================================
# ====================================================
### probar token
POST {{API_URL}}/api/v1/auth/token

#### prueba sign-in-google
POST {{API_URL}}/api/v1/auth/sign-in-google
Content-Type: application/json

{
  "email": "aasa@kayser.pe",
  "authID": "aaaaddddasjssssfjsdñad"
}

#### prueba sign-in-credentials
POST {{API_URL}}/api/v1/auth/sign-in-credentials
Content-Type: application/json

{
  "email": "aaaa@gmail.com",
  "password": "1234"
}

# ==============================================================================
# ==============================================================================
#Se necesita TOKEN para acceder a los modulos
### prueba modulos
GET {{API_URL}}/api/v1/modules
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NzYwOTM4NTgsImV4cCI6MTc3NjEwMTA1OCwiYXVkIjoiZXh0ZXJuYWwtc2VydmljZXMiLCJpc3MiOiJBcmNoZS1hcGkifQ.ZkdU8xr0OFa0CzGrjy-i3b1AUHDEtG7pPjT0YHNrDLE
