# docker-compose.yml
services:
  app:
    image: jsherrcode/api-arche:latest
    container_name: api-arche
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - shared_network
    restart: unless-stopped

networks:
  shared_network:
    external: true