# sonar-project.properties
sonar.projectKey=denis-kayser_Api-Arche
sonar.organization=denis-kayser
# sonar.organization=jsherrcode

# Información del proyecto
sonar.projectName=API Arche
sonar.projectVersion=1.0

# Rutas del código fuente
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js

# Lenguaje (ajusta según tu stack)
# sonar.language=js
# Si es TypeScript: sonar.language=ts

# Coverage (opcional, si tienes tests)
# sonar.javascript.lcov.reportPaths=coverage/lcov.info