
/**
 * Códigos de error - Autenticación y Autorización (4xx)
 */
export enum AuthErrorCode {
  MISSING_TOKEN = 'MISSING_TOKEN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  MISSING_API_KEY = 'MISSING_API_KEY',
  INVALID_API_KEY = 'INVALID_API_KEY',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  ACCESS_DENIED = 'ACCESS_DENIED',
  ROLE_REQUIRED = 'ROLE_REQUIRED'
}

/**
 * Códigos de error - Recursos (4xx)
 */
export enum ResourceErrorCode {
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  DUPLICATE_USERNAME = 'DUPLICATE_USERNAME'
}

/**
 * Códigos de error - Validación (4xx)
 */
export enum ValidationErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  MISSING_FIELD = 'MISSING_FIELD',
  INVALID_FORMAT = 'INVALID_FORMAT',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_PHONE = 'INVALID_PHONE',
  INVALID_DATE = 'INVALID_DATE',
  INVALID_NUMBER = 'INVALID_NUMBER',
  INVALID_URL = 'INVALID_URL',
  FIELD_TOO_SHORT = 'FIELD_TOO_SHORT',
  FIELD_TOO_LONG = 'FIELD_TOO_LONG',
  VALUE_OUT_OF_RANGE = 'VALUE_OUT_OF_RANGE'
}

/**
 * Códigos de error - Petición (4xx)
 */
export enum RequestErrorCode {
  BAD_REQUEST = 'BAD_REQUEST',
  INVALID_JSON = 'INVALID_JSON',
  UNSUPPORTED_MEDIA = 'UNSUPPORTED_MEDIA',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED'
}

/**
 * Códigos de error - Límites (4xx)
 */
export enum LimitErrorCode {
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  MAX_RETRIES_EXCEEDED = 'MAX_RETRIES_EXCEEDED'
}

/**
 * Códigos de error - Servidor (5xx)
 */
export enum ServerErrorCode {
  SERVER_ERROR = 'SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  DATABASE_TIMEOUT = 'DATABASE_TIMEOUT',
  CONNECTION_ERROR = 'CONNECTION_ERROR',
  REDIS_ERROR = 'REDIS_ERROR',
  QUEUE_ERROR = 'QUEUE_ERROR',
  EXTERNAL_API_ERROR = 'EXTERNAL_API_ERROR',
  EXTERNAL_API_TIMEOUT = 'EXTERNAL_API_TIMEOUT',
  FILE_SYSTEM_ERROR = 'FILE_SYSTEM_ERROR',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  DOWNLOAD_FAILED = 'DOWNLOAD_FAILED',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  DB_ERROR = 'DB_ERROR',
}

/**
 * Códigos especiales
 */
export enum SpecialCode {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  RETRY_LATER = 'RETRY_LATER',
  CONFLICT = 'CONFLICT',
  ALREADY_PROCESSED = 'ALREADY_PROCESSED',
  OPERATION_CANCELLED = 'OPERATION_CANCELLED',
  MAINTENANCE_MODE = 'MAINTENANCE_MODE'
}



export enum ErrorCode {
  // Genéricos
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',

  // Cliente
  MISSING_PARAMS = 'MISSING_PARAMS',

  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // Datos
  NOT_FOUND = 'NOT_FOUND',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  CONFLICT = 'CONFLICT',

  // Archivos
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
}