/**
 * Códigos de éxito (2xx)
 */
export enum SuccessCode {
  // Genéricos
  SUCCESS = 'SUCCESS',
  EMPTY = 'EMPTY',
  FETCHED = 'FETCHED',
  LIST_FETCHED = 'LIST_FETCHED',
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',

  // Autenticación
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  TOKEN_GENERATED = 'TOKEN_GENERATED',
  TOKEN_REFRESHED = 'TOKEN_REFRESHED',
  PASSWORD_RESET = 'PASSWORD_RESET',

  // Operaciones
  EMAIL_SENT = 'EMAIL_SENT',
  UPLOAD_SUCCESS = 'UPLOAD_SUCCESS',
  DOWNLOAD_SUCCESS = 'DOWNLOAD_SUCCESS',
  VALIDATION_PASSED = 'VALIDATION_PASSED'
}